<?php
require_role('teacher'); $me = user(); $title = 'My institutions'; $back = '?p=more';
$links = all('SELECT i.*,ti.status lst,ti.requested_by FROM teacher_institutions ti JOIN institutions i ON i.id=ti.institution_id WHERE ti.teacher_id=? ORDER BY ti.status, i.name', [$me['id']]);
$q = trim((string)get('q')); $found = $q !== '' ? all('SELECT * FROM institutions WHERE status="active" AND (name LIKE ? OR city LIKE ?) AND id NOT IN (SELECT institution_id FROM teacher_institutions WHERE teacher_id=?) ORDER BY name LIMIT 20', ["%$q%", "%$q%", $me['id']]) : [];
$btn = fn($iid, $do, $lbl, $cls = 'sm') => '<form method="post" style="display:inline">' . csrf_field() . '<input type="hidden" name="a" value="inst_teacher_respond"><input type="hidden" name="institution_id" value="' . (int)$iid . '"><input type="hidden" name="do" value="' . $do . '"><button class="btn ' . $cls . '">' . $lbl . '</button></form>';
?>
<div class="alert">Teach at one or more institutes on <?= e(setting('institute', 'EduMall')) ?>. You appear on their page, and they can assign courses to you. You can also run your own courses.</div>
<div class="list"><?php foreach ($links as $l): ?><div class="row"><span class="mi"><?= INST_TYPES[$l['type']][0] ?? '🏫' ?></span><div class="grow"><b><?= e($l['name']) ?></b><small><?= e($l['city']) ?> · <?= $l['lst'] === 'active' ? '✅ Teaching here' : ($l['requested_by'] === 'institute' ? '✉️ Invited you' : '⏳ Request sent') ?></small></div>
  <?php if ($l['lst'] === 'pending' && $l['requested_by'] === 'institute'): ?><?= $btn($l['id'], 'accept', '✓ Accept') ?> <?= $btn($l['id'], 'reject', '✕', 'sm ghost') ?><?php else: ?><?= $btn($l['id'], 'remove', $l['lst'] === 'active' ? 'Leave' : 'Cancel', 'sm ghost') ?><?php endif ?></div><?php endforeach ?></div>
<?php if (!$links): ?><p class="empty">You are not linked to any institute yet.</p><?php endif ?>
<form class="card"><input type="hidden" name="p" value="my_insts"><h3 style="margin-top:0">Find an institute to join</h3><div class="two"><input name="q" value="<?= e($q) ?>" placeholder="Institute name or city"><button class="btn">Search</button></div></form>
<div class="list"><?php foreach ($found as $i): ?><div class="row"><span class="mi"><?= INST_TYPES[$i['type']][0] ?? '🏫' ?></span><div class="grow"><b><?= e($i['name']) ?></b><small><?= e($i['city']) ?></small></div><form method="post"><?= csrf_field() ?><input type="hidden" name="a" value="inst_teacher_request"><input type="hidden" name="id" value="<?= $i['id'] ?>"><button class="btn sm">Request to join</button></form></div><?php endforeach ?></div>
