<?php
// Starter blog articles (original content). Idempotent by slug.
function blog_seed(): int {
    $author = function (string $email) { return (int)(val('SELECT id FROM users WHERE email=?', [$email]) ?: val('SELECT id FROM users WHERE role="admin" ORDER BY id LIMIT 1')); };
    $A = [
    ['How to Write a Band 7+ IELTS Writing Task 2 Essay', 'Languages', 'ayesha.siddiqui@demo.lms',
     'A simple four-paragraph structure, a planning method and the most common mistakes that keep students stuck at band 6.',
     "IELTS Writing Task 2 carries twice the marks of Task 1, so it deserves most of your practice time. The good news: a clear structure and a few habits can lift your score quickly.\n\n## Understand what the examiner marks\n\nYour essay is scored on four equal criteria:\n\n- **Task Response** — did you answer every part of the question with a clear position?\n- **Coherence and Cohesion** — is your essay logically organised with clear paragraphs?\n- **Lexical Resource** — do you use a good range of accurate vocabulary?\n- **Grammatical Range and Accuracy** — do you use varied sentences with few errors?\n\n## Use a four-paragraph structure\n\n1. **Introduction (2 sentences):** paraphrase the question, then state your opinion or what the essay will discuss.\n2. **Body paragraph 1:** one main idea, explained and supported with an example.\n3. **Body paragraph 2:** a second main idea (or the opposing view), explained with an example.\n4. **Conclusion (1–2 sentences):** restate your position in new words. Do not add new ideas.\n\n## Plan for five minutes\n\nBefore writing, underline the key words in the question and decide your answer. Write two main ideas and one example for each. Five minutes of planning saves you from going off-topic, which is the fastest way to lose marks.\n\n## Common mistakes to avoid\n\n- Memorised introductions that don't match the question\n- Writing under 250 words (you will lose marks)\n- Listing many ideas without explaining any of them\n- Using big words incorrectly — accuracy beats complexity\n\n## Practise the right way\n\nWrite one essay every two days, time yourself at 40 minutes, and compare it with a band 8 model answer. Note the linking words and topic sentences the model uses, then use them in your next essay.\n\n> Consistency beats intensity: ten carefully reviewed essays are worth more than thirty rushed ones."],
    ['MDCAT Preparation Plan: How to Study in the Last 90 Days', 'Exam Preparation', 'hira.naveed@demo.lms',
     'A week-by-week plan for the final three months before MDCAT, with tips on MCQ practice, revision and managing stress.',
     "Ninety days is enough time to make a big difference to your MDCAT score if you study with a plan. Here is a simple framework many successful students follow.\n\n## Weeks 1–6: Cover the syllabus\n\n- Divide the official syllabus by subject and chapter, and give each chapter a deadline.\n- Read the textbook topic first, then solve 40–60 MCQs on it the same day.\n- Biology usually carries the most marks, so give it the largest share of your time.\n- Keep a small notebook of facts you keep forgetting.\n\n## Weeks 7–10: Practise and revise\n\n- Take one full-length timed test every week, then two per week in the final month.\n- After each test, spend more time reviewing mistakes than you spent on the test itself.\n- Revise weak chapters using your notebook instead of re-reading whole books.\n\n## Weeks 11–13: Final revision\n\n- Focus on high-yield topics and your error notebook.\n- Do not start brand-new books now; trust the material you have studied.\n- Practise at the same time of day as the real exam.\n\n## MCQ strategy\n\n1. Read the question stem carefully before looking at options.\n2. Eliminate obviously wrong options first.\n3. Don't spend too long on one question — mark it and come back.\n\n## Look after yourself\n\nSleep 7–8 hours, eat properly and take short breaks. A tired brain makes silly mistakes. Always confirm exam dates, syllabus and rules from the official testing body's website, as they can change each year."],
    ['Python for Beginners: Write Your First Program in 10 Minutes', 'IT & Programming', 'usman.tariq@demo.lms',
     'Install Python, write your first lines of code and build a tiny marks calculator — no experience needed.',
     "Python is one of the easiest programming languages to start with. Its code reads almost like English, and it is used for websites, data analysis, automation and artificial intelligence.\n\n## Step 1: Install Python\n\nDownload Python from the official website python.org and run the installer. On Windows, tick **Add Python to PATH** before clicking Install. Then install a free editor such as VS Code.\n\n## Step 2: Your first line of code\n\nCreate a file called hello.py and type:\n\n> print(\"Assalam o Alaikum, Python!\")\n\nRun it and you will see the message on the screen. Congratulations — you are a programmer!\n\n## Step 3: Variables and input\n\nVariables store information. You can also ask the user to type something:\n\n> name = input(\"What is your name? \")\n> print(\"Welcome,\", name)\n\n## Step 4: A small marks calculator\n\n> marks = int(input(\"Enter your marks out of 100: \"))\n> if marks >= 80:\n>     print(\"Grade A\")\n> elif marks >= 60:\n>     print(\"Grade B\")\n> else:\n>     print(\"Keep practising!\")\n\nIn Python, the spaces at the start of a line (indentation) matter. They show which lines belong to the if statement.\n\n## What to learn next\n\n- Loops (for and while) to repeat tasks\n- Lists to store many values\n- Functions to reuse your code\n- A small project, such as a quiz game or expense tracker\n\nPractise for 30 minutes a day. Small, regular practice is the fastest way to learn programming."],
    ['10 Excel Formulas Every Student and Office Worker Should Know', 'IT & Programming', 'usman.tariq@demo.lms',
     'From SUM to XLOOKUP — the ten formulas that save hours on marks sheets, budgets and office reports.',
     "Microsoft Excel is one of the most requested skills in office jobs. You don't need to know hundreds of formulas — these ten cover most everyday tasks.\n\n## The basics\n\n1. **SUM** — adds numbers: =SUM(B2:B10)\n2. **AVERAGE** — the mean of a range: =AVERAGE(B2:B10)\n3. **MIN and MAX** — smallest and largest values: =MAX(B2:B10)\n4. **COUNT** — counts cells that contain numbers: =COUNT(B2:B10)\n\n## Making decisions\n\n5. **IF** — returns one value if a condition is true and another if false: =IF(C2>=50,\"Pass\",\"Fail\")\n6. **COUNTIF** — counts cells that meet a condition: =COUNTIF(D2:D40,\"Pass\")\n7. **SUMIF** — adds values that meet a condition, such as total expenses for one category: =SUMIF(A2:A100,\"Rent\",B2:B100)\n\n## Working with text and lookups\n\n8. **CONCAT** (or the & sign) — joins text: =A2&\" \"&B2\n9. **TRIM** — removes extra spaces from imported data: =TRIM(A2)\n10. **XLOOKUP** (or VLOOKUP in older Excel) — finds a value in a table, such as a student's marks by roll number.\n\n## Tips for using formulas\n\n- Every formula starts with an equals sign (=).\n- Drag the small square at the corner of a cell to copy a formula down a column.\n- Use $ to lock a cell reference, for example $B$1, when copying formulas.\n\nPractise by building a class marks sheet: total, percentage, grade with IF, and a pass count with COUNTIF. That one exercise uses most of these formulas."],
    ['How to Start Freelancing in Pakistan: A Beginner\'s Roadmap', 'Careers & Freelancing', 'usman.tariq@demo.lms',
     'Choose a skill, build a portfolio, create winning profiles and get your first client — a realistic step-by-step guide.',
     "Freelancing lets you earn by working for clients online. It is not a quick-money scheme — it is a real business that rewards skill and reliability. Here is a realistic roadmap.\n\n## 1. Choose one skill\n\nPick a skill that is in demand and that you enjoy, for example graphic design, web development, video editing, content writing or social media management. Focus on one skill for the first few months instead of trying everything.\n\n## 2. Learn by doing\n\nTake a structured course, then practise on real-looking projects. Build three to five samples for your portfolio, such as a logo set, a landing page or a social media campaign for an imaginary brand.\n\n## 3. Create your profiles\n\n- Use a clear, professional photo and a specific title, for example \"WordPress Website Developer\" rather than \"Freelancer\".\n- Write a short bio that explains how you help clients, not just your skills.\n- Add your portfolio samples.\n\n## 4. Win your first clients\n\n- Read the job post carefully and reply to what the client actually asked for.\n- Keep proposals short and personal; mention a relevant sample.\n- Consider a slightly lower price for your first few projects to earn reviews.\n\n## 5. Deliver like a professional\n\nCommunicate clearly, meet deadlines and ask for a review when the client is happy. Good reviews bring more work.\n\n## 6. Getting paid\n\nCheck which withdrawal methods each platform supports in Pakistan, compare fees, and keep records of your earnings for tax purposes.\n\n> Your first order is the hardest. After five good reviews, things become much easier."],
    ['FSc Physics: How to Solve Numericals Without Fear', 'Science', 'khalid.mehmood@demo.lms',
     'A five-step method for solving physics numericals, plus the unit and formula habits that prevent silly mistakes.',
     "Many students understand physics concepts but lose marks in numericals. The secret is not memorising more formulas — it is following the same method every time.\n\n## The five-step method\n\n1. **Read twice.** The first time to understand the situation, the second time to pick out the data.\n2. **Write the givens.** List every quantity with its symbol and unit, for example u = 0 m/s, a = 2 m/s², t = 5 s.\n3. **Write what is required.** For example, find s = ?\n4. **Choose the formula** that connects your givens to the unknown. Write it before substituting values.\n5. **Substitute and solve,** keeping units with every number, then box your final answer with its unit.\n\n## Unit habits\n\n- Convert everything to SI units before you start: km to m, g to kg, minutes to seconds.\n- Check that your final unit makes sense. If you are finding a force and get m/s, something went wrong.\n\n## Build a formula sheet\n\nFor each chapter, make a one-page sheet with every formula, what each symbol means and its unit. Revise it daily for five minutes.\n\n## Practise from past papers\n\nBoard exams often repeat question patterns. Solve the numericals from the last five years of past papers for each chapter, and you will recognise most questions in the exam.\n\n> Show every step. Even if your final answer is wrong, examiners often give marks for correct working."],
    ['Urdu Essay Writing: Structure and Tips for Higher Marks', 'Languages', 'tariq.jameel@demo.lms',
     'How to plan an Urdu essay, use couplets and quotations wisely, and present your work neatly for board exams.',
     "A good Urdu essay (mazmoon) is not about writing as many pages as possible. Examiners reward clear structure, relevant content and correct language.\n\n## Structure of an essay\n\n1. **Introduction (tamheed):** introduce the topic in a few lines. A relevant couplet at the start makes a strong impression.\n2. **Body:** divide the main content into three to five short paragraphs, each with a clear sub-heading.\n3. **Conclusion (ikhtitam):** summarise your main point and end with a thoughtful line or couplet.\n\n## Use couplets and quotations wisely\n\n- Learn a few couplets for common topics such as education, patriotism, hard work and science.\n- Use them only where they fit the paragraph — two or three are enough.\n- Write them correctly; a wrong couplet costs more than no couplet.\n\n## Language tips\n\n- Use simple, correct sentences rather than long, confusing ones.\n- Check gender (tazkeer-o-taneez) and spelling of common words.\n- Avoid repeating the same word; learn a few synonyms for frequent words.\n\n## Presentation\n\nWrite neatly, leave a line between paragraphs and underline sub-headings. A clean paper is easier to read and usually scores better.\n\n## Practise\n\nWrite one essay every week on a likely topic and ask your teacher to check it. Over a few months, your speed and confidence will improve noticeably."],
    ['10 Study Habits That Help You Score Higher in Every Exam', 'Study Tips', '',
     'Simple, proven habits — active recall, spaced revision, past papers and good sleep — that make studying more effective.',
     "Studying longer is not the same as studying better. These habits help you remember more in less time.\n\n## 1. Make a weekly timetable\n\nPlan which subject you will study each day. A written plan stops you from wasting time deciding what to do.\n\n## 2. Use active recall\n\nAfter reading a topic, close the book and try to explain it or write the key points from memory. Testing yourself is one of the most effective ways to learn.\n\n## 3. Revise in spaced intervals\n\nReview a topic after one day, then after a week, then after a month. Spaced revision moves information into long-term memory.\n\n## 4. Solve past papers\n\nPast papers show you the exam pattern and the topics that come up most often.\n\n## 5. Study in focused blocks\n\nWork for 25–45 minutes with your phone away, then take a 5–10 minute break.\n\n## 6. Teach someone else\n\nExplaining a topic to a friend or family member quickly shows you what you don't yet understand.\n\n## 7. Keep a mistakes notebook\n\nWrite down every mistake from tests and homework, and why you made it. Revise this notebook before exams.\n\n## 8. Sleep well\n\nYour brain organises what you learned while you sleep. Staying up all night before an exam usually lowers your score.\n\n## 9. Look after your body\n\nDrink water, eat regular meals and move a little every day. A healthy body supports a focused mind.\n\n## 10. Ask for help early\n\nIf you are stuck, ask your teacher or classmates. Small doubts become big problems if you ignore them.\n\n> Pick two habits from this list and practise them for two weeks. Then add two more."],
    ];
    $n = 0; $day = count($A);
    foreach ($A as [$title, $cat, $email, $excerpt, $content]) {
        $slug = slugify($title);
        if (val('SELECT id FROM posts WHERE slug=?', [$slug])) { $day--; continue; }
        q('INSERT INTO posts(title,slug,category,excerpt,content,author_id,published,created_at) VALUES(?,?,?,?,?,?,1,?)', [$title, $slug, $cat, $excerpt, $content, $author($email), date('Y-m-d H:i:s', strtotime('-' . ($day * 2) . ' days'))]);
        $n++; $day--;
    }
    return $n;
}
