CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  phone VARCHAR(30) DEFAULT '',
  password VARCHAR(255) NOT NULL,
  role ENUM('admin','teacher','student') NOT NULL DEFAULT 'student',
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS courses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  category_id INT NULL,
  teacher_id INT NULL,
  fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  color VARCHAR(10) DEFAULT '#4f46e5',
  published TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(teacher_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lessons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  video_url VARCHAR(500) DEFAULT '',
  content MEDIUMTEXT,
  attachment_url VARCHAR(500) DEFAULT '',
  sort INT NOT NULL DEFAULT 0,
  INDEX(course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS enrollments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  course_id INT NOT NULL,
  status ENUM('pending','active','completed') NOT NULL DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uc (user_id, course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS progress (
  user_id INT NOT NULL,
  lesson_id INT NOT NULL,
  done_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, lesson_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS quizzes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  pass_percent INT NOT NULL DEFAULT 50,
  INDEX(course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quiz_id INT NOT NULL,
  question TEXT NOT NULL,
  a VARCHAR(300) NOT NULL, b VARCHAR(300) NOT NULL,
  c VARCHAR(300) DEFAULT '', d VARCHAR(300) DEFAULT '',
  answer CHAR(1) NOT NULL,
  INDEX(quiz_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS attempts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quiz_id INT NOT NULL,
  user_id INT NOT NULL,
  score INT NOT NULL,
  total INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(user_id), INDEX(quiz_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  course_id INT NULL,
  amount DECIMAL(12,2) NOT NULL,
  method VARCHAR(40) DEFAULT 'Cash',
  note VARCHAR(255) DEFAULT '',
  paid_on DATE NOT NULL,
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  spent_on DATE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS announcements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NULL,
  title VARCHAR(200) NOT NULL,
  body TEXT,
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  k VARCHAR(60) PRIMARY KEY,
  v TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  course_id INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  method VARCHAR(40) NOT NULL,
  txn_ref VARCHAR(100) DEFAULT '',
  proof VARCHAR(120) DEFAULT '',
  note VARCHAR(255) DEFAULT '',
  status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  admin_note VARCHAR(255) DEFAULT '',
  payment_id INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(status), INDEX(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;

CREATE TABLE IF NOT EXISTS teacher_profiles (
  user_id INT PRIMARY KEY,
  photo VARCHAR(120) DEFAULT '',
  headline VARCHAR(200) DEFAULT '',
  bio TEXT,
  city VARCHAR(100) DEFAULT '',
  years INT DEFAULT 0,
  skills TEXT,
  languages VARCHAR(255) DEFAULT '',
  education MEDIUMTEXT,
  experience MEDIUMTEXT,
  certifications MEDIUMTEXT,
  achievements TEXT,
  linkedin VARCHAR(255) DEFAULT '',
  website VARCHAR(255) DEFAULT '',
  youtube VARCHAR(255) DEFAULT '',
  public TINYINT(1) NOT NULL DEFAULT 1,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;

CREATE TABLE IF NOT EXISTS expense_categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  icon VARCHAR(10) DEFAULT '💸'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS recurring_expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  category_id INT NULL,
  frequency ENUM('monthly','weekly','yearly') NOT NULL DEFAULT 'monthly',
  next_date DATE NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  note VARCHAR(255) DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;

CREATE TABLE IF NOT EXISTS posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  slug VARCHAR(220) NOT NULL UNIQUE,
  category VARCHAR(80) DEFAULT 'General',
  excerpt VARCHAR(400) DEFAULT '',
  content MEDIUMTEXT,
  cover VARCHAR(120) DEFAULT '',
  author_id INT NULL,
  published TINYINT(1) NOT NULL DEFAULT 1,
  views INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(published), INDEX(category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contact_messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) DEFAULT '',
  phone VARCHAR(40) DEFAULT '',
  subject VARCHAR(200) DEFAULT '',
  message TEXT,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;

CREATE TABLE IF NOT EXISTS batches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  teacher_id INT NULL,
  days VARCHAR(40) DEFAULT 'Mon,Tue,Wed,Thu,Fri',
  start_time TIME NULL,
  end_time TIME NULL,
  room VARCHAR(80) DEFAULT '',
  meet_link VARCHAR(300) DEFAULT '',
  start_date DATE NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(course_id), INDEX(teacher_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS batch_students (
  batch_id INT NOT NULL,
  user_id INT NOT NULL,
  added_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (batch_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS attendance (
  batch_id INT NOT NULL,
  user_id INT NOT NULL,
  att_date DATE NOT NULL,
  status CHAR(1) NOT NULL DEFAULT 'P',
  marked_by INT NULL,
  marked_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (batch_id, user_id, att_date),
  INDEX(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fee_vouchers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  course_id INT NULL,
  title VARCHAR(160) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  late_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  due_date DATE NOT NULL,
  status ENUM('unpaid','paid','cancelled') NOT NULL DEFAULT 'unpaid',
  paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  paid_on DATE NULL,
  payment_id INT NULL,
  plan_id INT NULL,
  period VARCHAR(7) DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(user_id), INDEX(status), INDEX(due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fee_plans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  due_day TINYINT NOT NULL DEFAULT 10,
  late_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
  generate_day TINYINT NOT NULL DEFAULT 1,
  active TINYINT(1) NOT NULL DEFAULT 1,
  last_period VARCHAR(7) DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS certificates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  course_id INT NOT NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  grade VARCHAR(40) DEFAULT '',
  issued_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  issued_by INT NULL,
  revoked TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uc (user_id, course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;

CREATE TABLE IF NOT EXISTS notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  body VARCHAR(500) DEFAULT '',
  link VARCHAR(255) DEFAULT '',
  icon VARCHAR(10) DEFAULT '🔔',
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(user_id, is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS assignments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NOT NULL,
  batch_id INT NULL,
  title VARCHAR(200) NOT NULL,
  instructions TEXT,
  attachment_url VARCHAR(500) DEFAULT '',
  due_at DATETIME NULL,
  max_marks INT NOT NULL DEFAULT 10,
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS submissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  assignment_id INT NOT NULL,
  user_id INT NOT NULL,
  answer TEXT,
  file VARCHAR(120) DEFAULT '',
  submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  marks DECIMAL(6,2) NULL,
  feedback VARCHAR(1000) DEFAULT '',
  graded_at DATETIME NULL,
  graded_by INT NULL,
  UNIQUE KEY ua (assignment_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NOT NULL,
  batch_id INT NULL,
  title VARCHAR(160) NOT NULL,
  exam_date DATE NULL,
  published TINYINT(1) NOT NULL DEFAULT 0,
  remarks_note VARCHAR(255) DEFAULT '',
  created_by INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(course_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exam_papers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  exam_id INT NOT NULL,
  subject VARCHAR(120) NOT NULL,
  max_marks INT NOT NULL DEFAULT 100,
  pass_marks INT NOT NULL DEFAULT 33,
  sort INT NOT NULL DEFAULT 0,
  INDEX(exam_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exam_marks (
  paper_id INT NOT NULL,
  user_id INT NOT NULL,
  marks DECIMAL(6,2) NULL,
  absent TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (paper_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS salary_rules (
  user_id INT PRIMARY KEY,
  type ENUM('fixed','per_student','percent') NOT NULL DEFAULT 'fixed',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS salary_slips (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  period VARCHAR(7) NOT NULL,
  basic DECIMAL(12,2) NOT NULL DEFAULT 0,
  bonus DECIMAL(12,2) NOT NULL DEFAULT 0,
  deduction DECIMAL(12,2) NOT NULL DEFAULT 0,
  net DECIMAL(12,2) NOT NULL DEFAULT 0,
  basis VARCHAR(255) DEFAULT '',
  status ENUM('unpaid','paid') NOT NULL DEFAULT 'unpaid',
  paid_on DATE NULL,
  method VARCHAR(40) DEFAULT '',
  expense_id INT NULL,
  note VARCHAR(255) DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY up (user_id, period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS parent_links (
  parent_id INT NOT NULL,
  student_id INT NOT NULL,
  relation VARCHAR(40) DEFAULT 'Parent',
  PRIMARY KEY (parent_id, student_id),
  INDEX(student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  category VARCHAR(80) DEFAULT 'Books',
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  compare_price DECIMAL(12,2) NULL,
  image VARCHAR(120) DEFAULT '',
  type ENUM('physical','digital') NOT NULL DEFAULT 'physical',
  file VARCHAR(120) DEFAULT '',
  stock INT NULL,
  course_id INT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(course_id), INDEX(active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  student_id INT NULL,
  status ENUM('pending','paid','processing','shipped','delivered','cancelled') NOT NULL DEFAULT 'pending',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  shipping DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  name VARCHAR(120) DEFAULT '',
  phone VARCHAR(40) DEFAULT '',
  address VARCHAR(300) DEFAULT '',
  city VARCHAR(80) DEFAULT '',
  pay_method VARCHAR(30) DEFAULT 'COD',
  proof VARCHAR(120) DEFAULT '',
  txn_ref VARCHAR(100) DEFAULT '',
  tracking VARCHAR(120) DEFAULT '',
  note VARCHAR(300) DEFAULT '',
  admin_note VARCHAR(300) DEFAULT '',
  payment_id INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(user_id), INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  qty INT NOT NULL DEFAULT 1,
  type VARCHAR(10) DEFAULT 'physical',
  INDEX(order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS teacher_payouts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  teacher_id INT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  method VARCHAR(40) DEFAULT 'Cash',
  note VARCHAR(255) DEFAULT '',
  paid_on DATE NOT NULL,
  created_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(teacher_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;
CREATE TABLE IF NOT EXISTS webauthn_creds (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  cred_id VARCHAR(255) NOT NULL UNIQUE,
  pubkey TEXT NOT NULL,
  alg INT NOT NULL,
  sign_count INT UNSIGNED DEFAULT 0,
  name VARCHAR(80) DEFAULT '',
  last_used DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;
CREATE TABLE IF NOT EXISTS login_attempts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(160) NOT NULL DEFAULT '',
  ip VARCHAR(45) NOT NULL DEFAULT '',
  at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(email), INDEX(ip), INDEX(at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
;
CREATE TABLE IF NOT EXISTS institutions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  type VARCHAR(20) NOT NULL DEFAULT 'school',
  city VARCHAR(80) DEFAULT '',
  address VARCHAR(255) DEFAULT '',
  about TEXT,
  programs TEXT,
  facilities TEXT,
  logo VARCHAR(120) DEFAULT '',
  cover VARCHAR(120) DEFAULT '',
  phone VARCHAR(40) DEFAULT '',
  whatsapp VARCHAR(40) DEFAULT '',
  email VARCHAR(160) DEFAULT '',
  website VARCHAR(200) DEFAULT '',
  fee_min INT DEFAULT 0,
  fee_max INT DEFAULT 0,
  established SMALLINT NULL,
  admissions_open TINYINT(1) DEFAULT 1,
  status VARCHAR(12) NOT NULL DEFAULT 'pending',
  featured TINYINT(1) DEFAULT 0,
  owner_id INT NULL,
  views INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(status), INDEX(type), INDEX(city)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS teacher_institutions (
  teacher_id INT NOT NULL,
  institution_id INT NOT NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'pending',
  requested_by VARCHAR(12) DEFAULT 'institute',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(teacher_id, institution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS admissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  institution_id INT NOT NULL,
  user_id INT NULL,
  student_name VARCHAR(120) NOT NULL,
  guardian_name VARCHAR(120) DEFAULT '',
  phone VARCHAR(40) NOT NULL,
  email VARCHAR(160) DEFAULT '',
  class_program VARCHAR(160) DEFAULT '',
  city VARCHAR(80) DEFAULT '',
  message TEXT,
  status VARCHAR(12) NOT NULL DEFAULT 'new',
  note VARCHAR(255) DEFAULT '',
  ip VARCHAR(45) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX(institution_id), INDEX(status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
